spring:
  application:
    name: confluent-kafka-spring-app
  kafka:
#   enable plaintext communication
    properties:
      security.protocol: PLAINTEXT
      sasl.mechanism: PLAIN
      schema.registry.url: http://localhost:8081

    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      properties:
        specific:
          avro:
            reader: true
topic:
  name: poems